import { useEffect, useRef, useState, type ChangeEvent, type ReactNode } from 'react';
import { ArrowLeft, Camera, Check, Box, FileImage, Heart, X, Wifi, Signal, BatteryFull, Download, Leaf } from 'lucide-react';

type Product = { name:string; category:string; ingredients:string; allergens:string; price:string; quantity:string; story:string; photo:string; team:string; design:string; live:boolean };
type Screen = 'add'|'details'|'story'|'review'|'packaging'|'design'|'saved'|'listing'|'catalogue';
const initial:Product = {name:'Heirloom Tomatoes',category:'Vegetables',ingredients:'Heirloom tomatoes',allergens:'None declared',price:'4.50',quantity:'1 lb',story:'Heirloom tomatoes from Green Valley Farm. Freshly picked and great for salads.',photo:'/images/tomatoes.jpg',team:'/images/farm.jpg',design:'',live:false};
const titles:Record<Screen,string> = {add:'Add Product',details:'Product Details',story:'Tell Us More',review:'Step title',packaging:'Step title',design:'Step title',saved:'Saved',listing:'Your Listing',catalogue:'Your Catalogue'};
const steps:Record<Screen,number> = {add:1,details:2,story:3,review:5,packaging:6,design:7,saved:6,listing:8,catalogue:8};
const subtitles:Record<Screen,string> = {add:'Add Product',details:'Product Details',story:'Tell Us More',review:'Review Your Product',packaging:'Product Packaging',design:'Your Packaging',saved:'Saved',listing:'Product Page',catalogue:'Your Catalogue'};
function load():Product { try {const item=JSON.parse(localStorage.getItem('farmily-draft') || 'null'); return item && typeof item.name === 'string' ? {...initial,...item} : initial;} catch {return initial;} }
function Button({children,onClick,secondary=false,disabled=false,className=''}:{children:ReactNode;onClick?:()=>void;secondary?:boolean;disabled?:boolean;className?:string}) {return <button type="button" className={`button ${secondary?'secondary':'primary'} ${className}`} onClick={onClick} disabled={disabled}>{children}</button>}
function Image({src,alt,className=''}:{src:string;alt:string;className?:string}) {return <img className={className} src={src} alt={alt}/>}
export default function App(){
 const [product,setProduct]=useState<Product>(load);
 const [screen,setScreen]=useState<Screen>('add');
 const [hasPhoto,setHasPhoto]=useState(false);
 const [scanning,setScanning]=useState(false);
 const [enhanced,setEnhanced]=useState(false);
 const [originalStory,setOriginalStory]=useState(product.story);
 const [sheet,setSheet]=useState(false);
 const [style,setStyle]=useState('Minimal');
 const [layout,setLayout]=useState('Front label');
 const [choice,setChoice]=useState<'new'|'existing'>('new');
 const [order,setOrder]=useState('Product First');
 const [liked,setLiked]=useState(false);
 const [notice,setNotice]=useState('');
 const [busy,setBusy]=useState(false);
 const [prompt,setPrompt]=useState('');
 const uploadRef=useRef<HTMLInputElement>(null);
 const uploadKind=useRef<'photo'|'team'|'design'>('photo');
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);if(noticeTimer.current)clearTimeout(noticeTimer.current)},[]);
 const tell=(text:string)=>{setNotice(text);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),3500)};
 const go=(next:Screen)=>{setScreen(next);window.scrollTo({top:0,behavior:'instant'});};
 const update=(key:keyof Product,value:string)=>setProduct(p=>({...p,[key]:value}));
 const save=(live=product.live)=>{const next={...product,live};setProduct(next);try{localStorage.setItem('farmily-draft',JSON.stringify(next));}catch{tell('Browser storage is full. Your changes remain available in this session.');}};
 const scan=()=>{setHasPhoto(true);setScanning(true);timer.current=setTimeout(()=>{setScanning(false);go('details')},1400)};
 const upload=(kind:'photo'|'team'|'design')=>{uploadKind.current=kind;uploadRef.current?.click()};
 const onUpload=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){tell('Please choose a JPG, PNG, or WebP image.');return;}if(file.size>2*1024*1024){tell('Please choose an image smaller than 2 MB.');return;}const kind=uploadKind.current;const reader=new FileReader();reader.onload=()=>{update(kind,String(reader.result));if(kind==='photo')scan();if(kind==='design')setChoice('existing');};reader.readAsDataURL(file);};
 const polish=(mode='polish')=>{if(!enhanced)setOriginalStory(product.story);setEnhanced(true);update('story',mode==='simplify'?'Fresh heirloom tomatoes, grown at Green Valley Farm. Picked with care and perfect for salads.':mode==='casual'?'Ten years ago, we planted our first heirloom tomatoes in our backyard. Today, we grow them for our neighbours.':'Ten years ago, we planted our first heirloom tomatoes in our backyard. Today, we grow them for our neighbours.');tell('Story updated with a local demo suggestion.');};
 const generate=()=>{setBusy(true);timer.current=setTimeout(()=>{setBusy(false);go('design');},1000);};
 const back=()=>{const previous:Record<Screen,Screen>={add:'catalogue',details:'add',story:'details',review:'story',packaging:'review',design:'packaging',saved:'design',listing:'saved',catalogue:'add'};go(previous[screen])};
 const valid=product.name.trim() && product.ingredients.trim() && product.quantity.trim() && Number(product.price)>0;
 const money=`$${Number(product.price||0).toFixed(2)}`;
 const mini=<div className="mini-product"><Image src={product.photo} alt={product.name}/><div><strong>{product.name}</strong><small>Green Valley Farm</small><span>{money} / {product.quantity}</span></div></div>;
 const photos=<><small>Personal / Team Photo</small><Image src={product.team} alt="The Green Valley Farm team in their garden" className="team-photo"/><small>Production / Process Photos</small><div className="photo-grid"><figure><Image src="/images/picking.jpg" alt="Picking ripe tomatoes from the vine"/><figcaption>✓ Picking tomatoes</figcaption></figure><figure><Image src="/images/packing.jpg" alt="Packing freshly harvested tomatoes"/><figcaption>✓ Packing tomatoes</figcaption></figure></div></>;
 const packagePreview=<div className={`package-preview ${style==='Natural'?'natural':''} ${layout==='Top label'?'top-label':''}`}><Image src={product.design || '/images/package.jpg'} alt="Paper produce box with a Green Valley Farm product label"/>{!product.design && <div className="package-label"><small>Green Valley Farm</small><span>{product.name}</span><small>{product.quantity} · {money}</small></div>}</div>;
 const productCard=<section className="card product-card"><div className="row"><span>Farmily</span><button className={`icon-button ${liked?'liked':''}`} onClick={()=>setLiked(!liked)} aria-label={liked?'Remove from favourites':'Add to favourites'} aria-pressed={liked}><Heart fill={liked?'currentColor':'none'}/></button></div><Image src={product.photo} alt={product.name} className="hero-photo"/><h2 className="plain-heading">{product.name}</h2><small>Green Valley Farm</small><div className="info-row"><span>Price</span><span>{money} / {product.quantity}</span></div><hr/><div className="info-row"><span>Allergens</span><span>{product.allergens || 'None declared'}</span></div><div className="info-row"><span>Ingredients</span><span>{product.ingredients}</span></div><small>✓ Ingredients and allergens checked by you.</small></section>;
 const storyCard=<section className="card"><h2 className="plain-heading">Your story</h2><p>{product.story || 'No story added.'}</p><hr/>{photos}</section>;
 const download=()=>{const escape=(v:string)=>v.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));const data=`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="360" viewBox="0 0 600 360"><rect width="600" height="360" rx="20" fill="#fffdf0"/><text x="42" y="60" fill="#415b50" font-family="Georgia" font-size="24">Green Valley Farm</text><text x="42" y="130" fill="#415b50" font-family="Georgia" font-size="32">${escape(product.name)}</text><text x="42" y="185" fill="#415b50" font-family="Arial" font-size="22">${escape(product.quantity)} · ${money}</text><text x="42" y="240" fill="#415b50" font-family="Arial" font-size="16">Ingredients: ${escape(product.ingredients)}</text><text x="42" y="280" fill="#415b50" font-family="Arial" font-size="16">Allergens: ${escape(product.allergens)}</text></svg>`;const url=URL.createObjectURL(new Blob([data],{type:'image/svg+xml'}));const link=document.createElement('a');link.href=url;link.download='farmily-product-label.svg';link.click();setTimeout(()=>URL.revokeObjectURL(url),5000);tell('Your product label has been downloaded.');};
 return <div className="app-shell"><input ref={uploadRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={onUpload} hidden/><div className="phone-status" aria-hidden="true"><b>9:41</b><div className="island"/><span><Signal size={19}/><Wifi size={18}/><BatteryFull size={25}/></span></div><header><button className="icon-button back" onClick={back} aria-label="Go back"><ArrowLeft/></button><h1>{titles[screen]}</h1></header><main><div className="progress"><small>{subtitles[screen]} · Step {steps[screen]} of 8</small><div role="progressbar" aria-label="Product setup progress" aria-valuenow={steps[screen]} aria-valuemin={0} aria-valuemax={8}><i style={{width:`${steps[screen]*12.5}%`}}/></div></div>
 {screen==='add' && <><div className="add-photo">{hasPhoto?<div className="scan-photo"><Image src={product.photo} alt="Product photo ready to scan"/>{scanning&&<><span className="scan-badge">✦ AI</span><div className="scan-line"/></>}</div>:<button className="photo-drop" onClick={()=>upload('photo')}><span className="camera-circle"><Camera size={44} strokeWidth={1.4}/><span>+</span></span><span>Take a clear photo of your product and its packaging</span></button>}</div>{scanning?<div className="reading" role="status"><h2>Reading your photo...</h2><span>▪ ▪ ▪</span></div>:<div className="two-buttons"><Button secondary onClick={()=>upload('photo')}>Take a photo</Button><Button secondary onClick={()=>upload('photo')}>Upload a photo</Button></div>}<div className="ai-callout"><strong>✦ Farmily AI</strong><p>We'll read your photo and fill in the details. You'll review everything next.</p></div><div className="actions"><Button disabled={scanning} onClick={hasPhoto?()=>go('details'):scan}>{hasPhoto?'Continue':'Try with sample photo'}</Button></div></>}
 {screen==='details' && <><div className="farm-summary"><Image src={product.photo} alt={product.name}/><div>Green Valley Farm<small>Check and edit your product information.</small></div></div><form onSubmit={e=>{e.preventDefault();if(valid)go('story')}}>{(['category','name','ingredients','allergens','quantity','price'] as const).map(key=><label className="field" key={key}><span>{({category:'Category',name:'Product name',ingredients:'Ingredients',allergens:'Allergens',quantity:'Quantity',price:'Price ($)'}[key])}</span>{key==='category'?<select value={product.category} onChange={e=>update(key,e.target.value)}><option>Vegetables</option><option>Fruit</option><option>Dairy</option><option>Bakery</option><option>Other</option></select>:<input required={key!=='allergens'} type={key==='price'?'number':'text'} min={key==='price'?'0.01':undefined} step={key==='price'?'0.01':undefined} value={product[key]} onChange={e=>update(key,e.target.value)}/>}</label>)}<label className="check-row"><input type="checkbox" required/>I've checked the ingredients and allergens</label><button type="submit" className="button primary" disabled={!valid}>Continue</button></form></>}
 {screen==='story' && <><p className="optional">Optional</p><section className="card"><h2>Your story</h2>{enhanced&&<div className="segmented"><button onClick={()=>{update('story',originalStory);setEnhanced(false)}}>Original</button><button className="selected">Enhanced</button></div>}<div className="story-input">{enhanced&&<span className="badge gold">✦ AI-enhanced</span>}<textarea aria-label="Your story" placeholder="Tell us your story. How did you start?" value={product.story} onChange={e=>update('story',e.target.value)}/></div>{enhanced?<><div className="chips"><button className="gold" onClick={()=>polish('casual')}>More casual</button><button onClick={()=>polish('simplify')}>Simplify</button></div><div className="prompt"><input aria-label="Story enhancement instructions" placeholder="How can Farmily AI help you?" value={prompt} onChange={e=>setPrompt(e.target.value)}/><button aria-label="Apply story suggestion" onClick={()=>{polish(prompt.toLowerCase().includes('simpl')?'simplify':'casual');setPrompt('')}}>✦</button></div><div className="two-buttons"><Button secondary onClick={()=>polish()}>✦ Try again</Button><Button onClick={()=>{setEnhanced(false);tell('Enhanced story selected.')}}>Use this</Button></div></>:<Button className="gold-button" disabled={!product.story.trim()} onClick={()=>polish()}>✦ Polish with AI</Button>}</section><section className="card"><h2>Photos</h2><h3>Personal / Team Photo</h3><small>You or your team at the farm</small><Image src={product.team} alt="Green Valley Farm team" className="team-photo"/><div className="two-buttons"><Button secondary onClick={()=>upload('team')}>Upload photo</Button><Button className="gold-button" onClick={()=>setSheet(true)}>✦ Enhance with AI</Button></div><h3>Production / Process Photos</h3><small>Show how your product is made</small><div className="photo-grid"><Image src="/images/picking.jpg" alt="Picking tomatoes"/><Image src="/images/packing.jpg" alt="Packing tomatoes"/></div></section><div className="actions"><Button onClick={()=>go('review')}>Continue</Button><Button secondary onClick={()=>go('review')}>Skip</Button></div></>}
 {screen==='review' && <><p>Check everything before continuing. You can still make changes.</p><div className="section-label"><span>PRODUCT INFORMATION<small>Required</small></span><button onClick={()=>go('details')}>Edit</button></div>{productCard}<div className="section-label"><span>ADDITIONAL DETAILS<small>Optional</small></span><button onClick={()=>go('story')}>Edit</button></div>{storyCard}<p className="fine-print">By confirming, you approve this information for your packaging and listing.</p><Button onClick={()=>go('packaging')}>Confirm &amp; Continue</Button></>}
 {screen==='packaging' && <><h2 className="plain-heading">Do you already have a packaging design?</h2><section className={`choice-card ${choice==='existing'?'active':''}`}><button className="choice-title" onClick={()=>setChoice('existing')} aria-pressed={choice==='existing'}><FileImage/><span className="radio-dot"/><h2 className="plain-heading">I already have a design</h2></button><p>Upload your existing design and improve it while keeping its original identity.</p><small>✦ AI Refine</small><Button secondary onClick={()=>upload('design')}>{product.design?'Replace existing design':'Upload existing design'}</Button>{product.design&&<Image src={product.design} alt="Uploaded packaging design" className="team-photo"/>}</section><section className={`choice-card ${choice==='new'?'active':''}`}><button className="choice-title" onClick={()=>setChoice('new')} aria-pressed={choice==='new'}><Box/><span className="radio-dot"/><h2 className="plain-heading">Create a new design</h2></button><p>Create packaging based on your product information and story.</p><small>✦ AI Generate</small>{choice==='new'&&<small>✓ Selected · Uses the information you confirmed</small>}</section>{mini}<div className="actions"><Button secondary onClick={()=>{save();go('saved')}}>Skip packaging</Button><Button disabled={busy || (choice==='existing'&&!product.design)} onClick={generate}>{busy?'Creating your design...':choice==='existing'?'Use existing design':'Generate Design'}</Button></div></>}
 {screen==='design' && <><div className="soft-callout"><span>✦ {product.design?'Your design':'AI-generated'}</span><small>Created from your product information and story.</small></div>{packagePreview}<small className="caption">Paper produce box · {product.quantity} · Label applied to front</small><div className="option-row"><span>Style</span><div className="chips">{['Minimal','Natural'].map(item=><button key={item} className={style===item?'selected':''} onClick={()=>setStyle(item)}>{item}</button>)}</div></div><div className="option-row"><label htmlFor="layout">Layout</label><select id="layout" value={layout} onChange={e=>setLayout(e.target.value)}><option>Front label</option><option>Top label</option></select></div><button className="text-button regenerate" onClick={()=>{setStyle(style==='Minimal'?'Natural':'Minimal');tell('Packaging style refreshed.')}}>✦ Regenerate</button><section className="card label-info"><small>LABEL INFORMATION</small><h2 className="plain-heading">{product.name}</h2><small>Green Valley Farm</small><div className="info-row"><span>Quantity</span><span>{product.quantity}</span></div><div className="info-row"><span>Price</span><span>{money}</span></div><p>{product.story}</p></section><p className="fine-print">Skip packaging / Don't use this design</p><div className="actions"><Button secondary onClick={download}><Download size={16}/> Download Design</Button><Button onClick={()=>{save();go('saved')}}>Use This Design</Button></div></>}
 {screen==='saved' && <div className="saved-screen"><div className="success-icon"><Check size={30}/></div><h2>Saved to your catalogue</h2><div className="saved-product">{mini}<span className="badge gold">{product.live?'Live':'Draft'}</span></div><p className="fine-print">Only you can see this until you publish.</p><div className="actions"><Button onClick={()=>go('listing')}>Continue</Button><Button secondary onClick={()=>go('catalogue')}>View catalogue</Button></div></div>}
 {screen==='listing' && <><div className="soft-callout">{product.live?<strong><Check size={21}/> Your listing is live</strong>:<><span>✦ AI-recommended</span><small>Based on your product and story, we recommend this structure.</small></>}</div>{!product.live&&<><div className="chips layout-chips">{['Product First','Story First','Process First'].map(item=><button key={item} className={order===item?'selected':''} onClick={()=>setOrder(item)}>{item}</button>)}</div><small className="caption">Product First recommended</small></>}<div className="section-label"><span>CUSTOMER PREVIEW</span><span className={`badge ${product.live?'live':''}`}>{product.live?'Live':'Not published'}</span></div>{order==='Story First'?<>{storyCard}{productCard}</>:order==='Process First'?<><section className="card">{photos}</section>{productCard}</>:productCard}<section className="card"><h2 className="plain-heading">Packaging</h2>{packagePreview}</section>{order!=='Story First'&&storyCard}<div className="actions">{product.live?<><Button secondary onClick={()=>{save(false);tell('Listing returned to a local draft.')}}>Return to draft</Button><Button onClick={()=>go('catalogue')}>View catalogue</Button></>:<><Button secondary onClick={()=>{save();go('saved')}}>Save draft</Button><Button onClick={()=>{save(true);tell('Your listing is live in this local prototype.');window.scrollTo({top:0,behavior:'smooth'})}}>Publish</Button></>}</div></>}
 {screen==='catalogue'&&<><div className="catalogue-heading"><Leaf size={28}/><h2>Green Valley Farm</h2></div><button className="catalogue-product" onClick={()=>go('listing')}>{mini}<span className={`badge ${product.live?'live':'gold'}`}>{product.live?'Live':'Draft'}</span></button><Button onClick={()=>{setProduct(initial);setHasPhoto(false);go('add')}}>Add product</Button></>}
 </main>{notice&&<div className="toast" role="status">{notice}</div>}{sheet&&<div className="modal-backdrop" onClick={()=>setSheet(false)}><section className="sheet" role="dialog" aria-modal="true" aria-labelledby="enhance-title" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="icon-button sheet-close" aria-label="Close enhancement preview" onClick={()=>setSheet(false)}><X/></button><h2 id="enhance-title">✦ Enhance with AI</h2><span className="badge">Personal / Team Photo</span><Image src={product.team} alt="Team photo enhancement preview" className="team-photo enhanced-photo"/><div className="segmented"><button>Original</button><button className="selected">Enhanced</button></div><div className="chips"><button className="gold" onClick={()=>tell('Lighting preview selected.')}>Improve lighting</button><button onClick={()=>tell('Background preview selected.')}>Clean background</button><button onClick={()=>tell('Clarity preview selected.')}>Improve clarity</button></div><small>Local preview · photo enhancement is simulated.</small><div className="two-buttons"><Button secondary onClick={()=>tell('Preview refreshed.')}>✦ Try again</Button><Button onClick={()=>{setSheet(false);tell('Photo preview selected.')}}>Use this</Button></div></section></div>}<div className="home-indicator" aria-hidden="true"/></div>;
}

